server:
  port: 8090

spring:
  application:
    name: userApp
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
      url: jdbc:postgresql://localhost:5432/byteforge
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver

  jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: create-drop
      generate-ddl: true
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true
