apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # MongoDB Configuration
  MONGODB_HOST: "mongodb"  # Usually service name, not pod name like "mongodb-0.mongodb"
  MONGODB_PORT: "27017"
  MONGODB_POST_DATABASE: "postdb"
  MONGODB_NOTIFICATION_DATABASE: "notificationdb"
  MONGODB_URI_NOTIFICATION: "mongodb://mongodb:password@mongodb:27017/notificationdb?authSource=admin"
  MONGODB_URI_POST: "mongodb://mongodb:password@mongodb:27017/postdb?authSource=admin"


  # PostgreSQL Configuration
  POSTGRES_HOST: "postgres"  # Use the service name instead of statefulset pod name
  POSTGRES_PORT: "5432"
  POSTGRES_USER_DATABASE: "userdb"
  POSTGRES_MODERATOR_DATABASE: "moderatordb"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "1234"

  # RabbitMQ Configuration
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: "guest"

  # Redis Configuration
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  # Service Ports
  USER_SERVICE_PORT: "8080"
  POST_SERVICE_PORT: "8081"
  MODERATOR_SERVICE_PORT: "8082"
  NOTIFICATION_SERVICE_PORT: "8083"
