apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderator-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moderator-app
  template:
    metadata:
      labels:
        app: moderator-app
    spec:
      containers:
      - name: moderator-app
        image: ahmedhesham890/moderator-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: moderator-app
spec:
  selector:
    app: moderator-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 