spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cache:
    type: redis
    redis:
      cache-null-values: false
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5000
          max-attempts: 3
          multiplier: 2
          max-interval: 30000

server:
  port: 8081

logging:
  level:
    com.example.FinalProject: INFO
    com.example.FinalProject.events: ${LOGGING_LEVEL_COM_EXAMPLE_FINALPROJECT_EVENTS}
    org.springframework.data.mongodb: WARN
    org.springframework.amqp: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 