services:
  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: byteforge
    ports:
      - "5433:5432"
  redis_cache:
    image: redis:latest
    container_name: redisCache_sessions
    ports:
      - "6379:6379"
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisInsight_sessions
    ports:
      - "5540:5540"
    restart: always

